//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetasequoiaPipeline {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MetasequoiaPipeline.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to このファイル&quot;{0}&quot;はメタセコイアファイルではありません。.
        /// </summary>
        internal static string InvalidFileFormat {
            get {
                return ResourceManager.GetString("InvalidFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 指定されたインデックスを使用している辺が見つかりません。データ情報が壊れている可能性があります.
        /// </summary>
        internal static string MqFaceEdgeNotFounded {
            get {
                return ResourceManager.GetString("MqFaceEdgeNotFounded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MqMeshBuilder.Beginが二度呼ばれました。MqMeshBuilder.Endを呼び出してください。.
        /// </summary>
        internal static string MqMeshBuilderBeginTwice {
            get {
                return ResourceManager.GetString("MqMeshBuilderBeginTwice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 指定された辺は面の中には含まれません。データ情報が壊れている可能性があります.
        /// </summary>
        internal static string NotFoundEdge {
            get {
                return ResourceManager.GetString("NotFoundEdge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to このメタセコイアファイル&quot;{0}&quot;のバージョン は&quot;{1}&quot;で、サポートされていないバージョンです。.
        /// </summary>
        internal static string NotSupportedVersionFile {
            get {
                return ResourceManager.GetString("NotSupportedVersionFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to このVertexChannelにはNameアトリビュートが存在しません。.
        /// </summary>
        internal static string NoVertexChannelName {
            get {
                return ResourceManager.GetString("NoVertexChannelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to オブジェクト &quot;{0}&quot; 内でどのボーンにも属していない頂点があります。インポーターは仮のボーン「#FxiedBone」を生成して対処しますが、もとのモデルデータを修正するようにしてください。.
        /// </summary>
        internal static string OrphanedVertex {
            get {
                return ResourceManager.GetString("OrphanedVertex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 模様テクスチャ&quot;{0}&quot;とアルファテクスチャ&quot;{1}&quot;のサイズ違います。合成するには二つとも同じサイズである必要があります。.
        /// </summary>
        internal static string TextureSizeMismatched {
            get {
                return ResourceManager.GetString("TextureSizeMismatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (0)行目: TrialNoiseチャンクがあります。読み込みを中止します。.
        /// </summary>
        internal static string TrialChunkDetected {
            get {
                return ResourceManager.GetString("TrialChunkDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}行目: サポートされていないチャンク \&quot;{1}\&quot; です。.
        /// </summary>
        internal static string UnknownChunk {
            get {
                return ResourceManager.GetString("UnknownChunk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 指定された文字列、あるいはコードページ &quot;{0}&quot; からエンコーディング情報を生成できませんでした。正しい文字コードを指定してください。.
        /// </summary>
        internal static string UnknownEncoding {
            get {
                return ResourceManager.GetString("UnknownEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未対応の拡張子&quot;{0}&quot;です。読み込めるのは拡張子が&quot;.mqo&quot;または&quot;.xmq&quot;のファイルです。.
        /// </summary>
        internal static string UnknownFileType {
            get {
                return ResourceManager.GetString("UnknownFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}行目: サポートされていないトークン&quot;{1}&quot; です。.
        /// </summary>
        internal static string UnknownToken {
            get {
                return ResourceManager.GetString("UnknownToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to このVertexChannel &quot;{0}&quot;はサポートされていません。.
        /// </summary>
        internal static string UnknownVertexChannel {
            get {
                return ResourceManager.GetString("UnknownVertexChannel", resourceCulture);
            }
        }
    }
}
